# Conda environment
name: intentprompt
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.11.8
  - pandas=2.1.1
  - pyyaml
  - pip
  - pip:
      - openai==1.59.0
      - vertexai==1.74.0
      - anthropic==0.49.0